version: 2
updates:
  # Monitor npm dependencies
  - package-ecosystem: "npm"
    directory: "/" # Root directory where package.json is located
    schedule:
      interval: "weekly" # Options: "daily", "weekly", "monthly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"

  # Monitor GitHub Actions versions
  - package-ecosystem: "github-actions"
    directory: "/" # GitHub workflows are in .github/workflows
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
